import React from 'react'

export default function
    () {
    return (
        <div className='px-5 py-5  mx-5 my-20 grid grid-cols-3 gap-6'>
            <div className='bg-[#FFF] max-h-32 overflow-y-auto'> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam blanditiis ea bea laboriosam facere, excepturi accusantium. Necessitatibus, fuga, aut adipisci sed quibusdam eos? Blanditiis, sapiente deleniti provident veritatis aut fugit architecto exercitationem reprehenderit quisquam doloribus animi totam atque quae facilis velit temporibus asperiores dicta quidem eligendi vitae recusandae molestiae enim reiciendis quibusdam? Asperiores nesciunt distinctio exercitationem nam unde commodi blanditiis, eius natus autem voluptas id.</div>
            <div className='bg-[#FFF]'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum ab eos a exercitati, inventore blanditiis consequuntur excepturi in recusandcusantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
            <div className='bg-[#FFF]'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum ab eos a exercitatio inventore blanditiis consequuntur excepturi in recusandausantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
            <div className='bg-[#FFF]'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum ab eos a exercitatio inventore blanditiis consequuntur excepturi in recusandausantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
            <div className='bg-[#FFF]'> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam blanditiis ea bea laboriosam facere, excepturi accusantium. Necessitatibus, fuga, aut adipisci sed quibusdam eos? Blanditiis, sapiente deleniti provident veritatis aut fugit architecto exercitationem reprehenderit quisquam doloribus animi totam atque quae facilis velit temporibus asperiores dicta quidem eligendi vitae recusandae molestiae enim reiciendis quibusdam? Asperiores nesciunt distinctio exercitationem nam unde commodi blanditiis, eius natus autem voluptas id.</div>
            <div className='bg-[#FFF]'> Lorem ipsum dolor sit amet,consectetur adipisicing elit. Dolorum ab eos a exercitati, inventore blanditiis consequuntur excepturi in recusandcusantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
            <div className='bg-[#FFF]'>Lorem ipsum dolor sit amet,consectetur adipisicing elit. Dolorum ab eos a exercitatio inventore blanditiis consequuntur excepturi in recusandausantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
            <div className='bg-[#FFF]'>Lorem ipsum dolor sit amet,consectetur adipisicing elit. Dolorum ab eos a exercitatio inventore blanditiis consequuntur excepturi in recusandausantium? Tempora quae error reprehenderit officia deleniti quasi quam, veniam ea, dolorum nobis sequi minima quod, optio velit ut sit obcaecati mollitia qui odit adipisci! Rem facilis officiis, totam doloremque dolorem quibusdam sint. Fugit officia iure reiciendis velit ipsa?</div>
        </div>
    )
}
